
####################################################################################
# Generated by PlanAhead 14.6 built on 'Wed Jun  5 11:14:03 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'zeboard.ucf'
####################################################################################

# "GCLK"
set_property PACKAGE_PIN Y9 [get_ports clk100]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:1
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk100' has been applied to the port object 'clk100'.
set_property IOSTANDARD LVCMOS33 [get_ports clk100]

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:3
create_clock -name clk100 -period 10.000 [get_ports clk100]

# VGA out
# "VGA-B1"
set_property PACKAGE_PIN Y21 [get_ports {vga_b[0]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:6
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_b[0]' has been applied to the port object 'vga_b[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
# "VGA-B2"
set_property PACKAGE_PIN Y20 [get_ports {vga_b[1]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:7
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_b[1]' has been applied to the port object 'vga_b[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
# "VGA-B3"
set_property PACKAGE_PIN AB20 [get_ports {vga_b[2]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:8
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_b[2]' has been applied to the port object 'vga_b[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
# "VGA-B4"
set_property PACKAGE_PIN AB19 [get_ports {vga_b[3]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:9
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_b[3]' has been applied to the port object 'vga_b[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
# "VGA-G1"
set_property PACKAGE_PIN AB22 [get_ports {vga_g[0]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:10
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_g[0]' has been applied to the port object 'vga_g[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
# "VGA-G2"
set_property PACKAGE_PIN AA22 [get_ports {vga_g[1]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:11
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_g[1]' has been applied to the port object 'vga_g[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
# "VGA-G3"
set_property PACKAGE_PIN AB21 [get_ports {vga_g[2]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:12
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_g[2]' has been applied to the port object 'vga_g[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
# "VGA-G4"
set_property PACKAGE_PIN AA21 [get_ports {vga_g[3]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:13
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_g[3]' has been applied to the port object 'vga_g[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
# "VGA-R1"
set_property PACKAGE_PIN V20 [get_ports {vga_r[0]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:14
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_r[0]' has been applied to the port object 'vga_r[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
# "VGA-R2"
set_property PACKAGE_PIN U20 [get_ports {vga_r[1]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:15
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_r[1]' has been applied to the port object 'vga_r[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
# "VGA-R3"
set_property PACKAGE_PIN V19 [get_ports {vga_r[2]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:16
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_r[2]' has been applied to the port object 'vga_r[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
# "VGA-R4"
set_property PACKAGE_PIN V18 [get_ports {vga_r[3]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:17
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_r[3]' has been applied to the port object 'vga_r[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
# "VGA-HS"
set_property PACKAGE_PIN AA19 [get_ports vga_hsync]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:18
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_hsync' has been applied to the port object 'vga_hsync'.
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
# "VGA-VS"
set_property PACKAGE_PIN Y19 [get_ports vga_vsync]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:19
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_vsync' has been applied to the port object 'vga_vsync'.
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

set_property PACKAGE_PIN N15 [get_ports btnl]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:21
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnl' has been applied to the port object 'btnl'.
set_property IOSTANDARD LVCMOS18 [get_ports btnl]
set_property PACKAGE_PIN P16 [get_ports btnc]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:22
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnc' has been applied to the port object 'btnc'.
set_property IOSTANDARD LVCMOS18 [get_ports btnc]
set_property PACKAGE_PIN R18 [get_ports btnr]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:23
# The conversion of 'IOSTANDARD' constraint on 'net' object 'btnr' has been applied to the port object 'btnr'.
set_property IOSTANDARD LVCMOS18 [get_ports btnr]

# JA0
set_property PACKAGE_PIN Y11 [get_ports ov7670_pwdn]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:25
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_pwdn' has been applied to the port object 'ov7670_pwdn'.
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pwdn]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:25
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_pwdn' has been applied to the port object 'ov7670_pwdn'.
set_property SLEW SLOW [get_ports ov7670_pwdn]
# JA4
set_property PACKAGE_PIN AB11 [get_ports ov7670_reset]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:26
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_reset' has been applied to the port object 'ov7670_reset'.
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_reset]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:26
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_reset' has been applied to the port object 'ov7670_reset'.
set_property SLEW SLOW [get_ports ov7670_reset]
# JA1
set_property PACKAGE_PIN AA11 [get_ports {ov7670_data[0]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:27
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[0]' has been applied to the port object 'ov7670_data[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[0]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:27
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[0]' has been applied to the port object 'ov7670_data[0]'.
set_property SLEW SLOW [get_ports {ov7670_data[0]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:27
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[0]' has been applied to the port object 'ov7670_data[0]'.
set_property PULLDOWN true [get_ports {ov7670_data[0]}]
# JA5
set_property PACKAGE_PIN AB10 [get_ports {ov7670_data[1]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:28
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[1]' has been applied to the port object 'ov7670_data[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[1]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:28
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[1]' has been applied to the port object 'ov7670_data[1]'.
set_property SLEW SLOW [get_ports {ov7670_data[1]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:28
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[1]' has been applied to the port object 'ov7670_data[1]'.
set_property PULLDOWN true [get_ports {ov7670_data[1]}]
# JA2
set_property PACKAGE_PIN Y10 [get_ports {ov7670_data[2]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:29
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[2]' has been applied to the port object 'ov7670_data[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[2]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:29
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[2]' has been applied to the port object 'ov7670_data[2]'.
set_property SLEW SLOW [get_ports {ov7670_data[2]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:29
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[2]' has been applied to the port object 'ov7670_data[2]'.
set_property PULLDOWN true [get_ports {ov7670_data[2]}]
# JA6
set_property PACKAGE_PIN AB9 [get_ports {ov7670_data[3]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:30
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[3]' has been applied to the port object 'ov7670_data[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[3]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:30
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[3]' has been applied to the port object 'ov7670_data[3]'.
set_property SLEW SLOW [get_ports {ov7670_data[3]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:30
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[3]' has been applied to the port object 'ov7670_data[3]'.
set_property PULLDOWN true [get_ports {ov7670_data[3]}]
# JA3
set_property PACKAGE_PIN AA9 [get_ports {ov7670_data[4]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:31
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[4]' has been applied to the port object 'ov7670_data[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[4]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:31
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[4]' has been applied to the port object 'ov7670_data[4]'.
set_property SLEW SLOW [get_ports {ov7670_data[4]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:31
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[4]' has been applied to the port object 'ov7670_data[4]'.
set_property PULLDOWN true [get_ports {ov7670_data[4]}]
# JA7
set_property PACKAGE_PIN AA8 [get_ports {ov7670_data[5]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:32
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[5]' has been applied to the port object 'ov7670_data[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[5]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:32
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[5]' has been applied to the port object 'ov7670_data[5]'.
set_property SLEW SLOW [get_ports {ov7670_data[5]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:32
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[5]' has been applied to the port object 'ov7670_data[5]'.
set_property PULLDOWN true [get_ports {ov7670_data[5]}]

# JB0
set_property PACKAGE_PIN W12 [get_ports {ov7670_data[6]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:34
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[6]' has been applied to the port object 'ov7670_data[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[6]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:34
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[6]' has been applied to the port object 'ov7670_data[6]'.
set_property SLEW SLOW [get_ports {ov7670_data[6]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:34
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[6]' has been applied to the port object 'ov7670_data[6]'.
set_property PULLDOWN true [get_ports {ov7670_data[6]}]
# JB4
set_property PACKAGE_PIN V12 [get_ports {ov7670_data[7]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:35
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_data[7]' has been applied to the port object 'ov7670_data[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data[7]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:35
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_data[7]' has been applied to the port object 'ov7670_data[7]'.
set_property SLEW SLOW [get_ports {ov7670_data[7]}]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:35
# The conversion of 'PULL' constraint on 'net' object 'ov7670_data[7]' has been applied to the port object 'ov7670_data[7]'.
set_property PULLDOWN true [get_ports {ov7670_data[7]}]
# JB1
set_property PACKAGE_PIN W11 [get_ports ov7670_xclk]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:36
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_xclk' has been applied to the port object 'ov7670_xclk'.
set_property IOSTANDARD LVTTL [get_ports ov7670_xclk]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:36
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_xclk' has been applied to the port object 'ov7670_xclk'.
set_property SLEW SLOW [get_ports ov7670_xclk]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:36
# The conversion of 'PULL' constraint on 'net' object 'ov7670_xclk' has been applied to the port object 'ov7670_xclk'.
set_property PULLDOWN true [get_ports ov7670_xclk]
# JB5
set_property PACKAGE_PIN W10 [get_ports ov7670_pclk]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:37
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_pclk' has been applied to the port object 'ov7670_pclk'.
set_property IOSTANDARD LVTTL [get_ports ov7670_pclk]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:37
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_pclk' has been applied to the port object 'ov7670_pclk'.
set_property SLEW SLOW [get_ports ov7670_pclk]
# JB2
set_property PACKAGE_PIN V10 [get_ports ov7670_href]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:38
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_href' has been applied to the port object 'ov7670_href'.
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_href]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:38
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_href' has been applied to the port object 'ov7670_href'.
set_property SLEW SLOW [get_ports ov7670_href]
# JB6
set_property PACKAGE_PIN V9 [get_ports ov7670_vsync]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:39
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_vsync' has been applied to the port object 'ov7670_vsync'.
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_vsync]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:39
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_vsync' has been applied to the port object 'ov7670_vsync'.
set_property SLEW SLOW [get_ports ov7670_vsync]
# JB3
set_property PACKAGE_PIN W8 [get_ports ov7670_siod]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:40
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_siod' has been applied to the port object 'ov7670_siod'.
set_property IOSTANDARD LVTTL [get_ports ov7670_siod]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:40
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_siod' has been applied to the port object 'ov7670_siod'.
set_property SLEW SLOW [get_ports ov7670_siod]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:40
# The conversion of 'PULL' constraint on 'net' object 'ov7670_siod' has been applied to the port object 'ov7670_siod'.
set_property PULLUP true [get_ports ov7670_siod]
# JB7
set_property PACKAGE_PIN V8 [get_ports ov7670_sioc]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:41
# The conversion of 'IOSTANDARD' constraint on 'net' object 'ov7670_sioc' has been applied to the port object 'ov7670_sioc'.
set_property IOSTANDARD LVTTL [get_ports ov7670_sioc]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:41
# The conversion of 'SLEW' constraint on 'net' object 'ov7670_sioc' has been applied to the port object 'ov7670_sioc'.
set_property SLEW SLOW [get_ports ov7670_sioc]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov7670_pclk]

set_property PACKAGE_PIN T22 [get_ports config_finished]
# G:/Ov7670_fr_zedboard/ov7670_fr/zeboard.ucf:45
# The conversion of 'IOSTANDARD' constraint on 'net' object 'config_finished' has been applied to the port object 'config_finished'.
set_property IOSTANDARD LVTTL [get_ports config_finished]

